pipeline:
  name: docker-utility-images
  identifier: dockerutilityimages
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        repoName: docker-utility-images
        build: <+input>
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: hello
                  identifier: hello
                  spec:
                    shell: Bash
                    command: echo "world"
  delegateSelectors:
    - image-flow-delegate
