pipeline:
  name: pr-pipeline
  identifier: prpipeline
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        repoName: docker-utility-images
        build: <+input>
  stages:
    - stage:
        name: Lint and Build
        identifier: LintAndBuild
        strategy:
          matrix:
            container:
              - hello-a
              - hello-b
              - hello-c
          maxConcurrency: 10
        template:
          templateRef: lintbuildstage
          versionLabel: "1"
  delegateSelectors:
    - image-flow-delegate
